### ISSUE TITLE
Ability to disable ### Dependencies header or customize header

### ISSUE THREAD

**Issue by ChristopherBeltran** [dangoslen/dependabot-changelog-helper#200]
Based on https://keepachangelog.com/en/1.1.0/, dependency upgrades are simply listed within a `### Changed` header, not a `### Dependencies` header.  This has caused compatibility issues when attempting to use other GitHub Actions that strictly adhere to the Keep A Changelog format.  Would it be possible to add the ability to disable adding the header, or to be able to choose whether to list the dependency upgrades within ` ### Dependencies ` or `### Changed` ?

**Comment by dangoslen** [comment]
This is a great idea @ChristopherBeltran. And I don't think it would be difficult to implement. You can define this as an option to the action with a default for the existing behavior `### Dependencies` with the capability to define a different section.

Maybe something like this?

```yaml:
      - uses: dangoslen/dependabot-changelog-helper@v3
        with:
          version: ${{ needs.setup.outputs.version }}
          activationLabel: 'dependabot'
          changelogPath: './CHANGELOG.md'
          sectionHeader: 'DEPENDENCIES' # Or whatever you want
```
